version: "3.7"
services:
  redisai:
    image: redislabs/redismod
    expose:
      - "6379"
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redisai
    expose:
      - "7777"
    ports:
      - "7777:7777"
    command: python redisai-py.py
    restart: on-failure
 